version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails db:setup && ./bin/rails s -p 3000 -b '0.0.0.0'"
    environment:
      WELCOME_POSTGRES_HOST: db
      WELCOME_POSTGRES_USER: postgres
      WELCOME_POSTGRES_PASSWORD: postgres
    volumes:
      - .:/var/www/welcome-chat
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - db
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.4
    volumes:
      - redis:/var/lib/redis
    ports:
      - "6379:6379"

  db:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  redis:
  postgres:
