default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch('WELCOME_POSTGRES_HOST', '') %>
  username: <%= ENV.fetch('WELCOME_POSTGRES_USER', 'welcome') %>
  password: <%= ENV.fetch('WELCOME_POSTGRES_PASSWORD', 'ur_welcome') %>

development:
  <<: *default
  database: welcome_chat_development

test:
  <<: *default
  database: welcome_chat_test

production:
  <<: *default
  database: welcome_chat_production
